[package]
name = "grav_rogue"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.7.1"
crossbeam = "0.8.4"
glam = "0.30.4"
imgui = "0.12.0"
raylib = "5.5.1"
raylib_imgui_rs = "0.4.0"
rayon = "1.10.0"
shipyard = {version = "0.8.1", features = ["parallel"]}
